version: "3.8"
services:
    server:
        image: server
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: node-c
        ports:
            - 9000:9000
        depends_on:
            - mydb
    nginx:
        image: reverse-proxy
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: reverse-proxy
        ports:
            - 8080:8080  
        
    mydb:
        container_name: mydb
        platform: linux/x86_64
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root